### ISSUE TITLE
Cannot use function keys (alt, option, command, control, etc) in app

### ISSUE THREAD

**Issue by mattequisolve** [ericmason/tsheets_desktop#1]
Tried to paste my password from Lastpass into the password field and no dice (doesn't accept any of the function-type keys). Also doesn't let you right click.

**Comment by mattequisolve** [comment]
Updated issue to make it globally about not being about to use keys like alt, option, command, control, etc. 

Keeps you from being able to paste into the password field as described above and also keeps you from being able to do an in-page search, which I use to find the company name.

**Comment by roseg43** [comment]
Yep, can confirm this issue. This is currently a dealbreaker for me, seeing as I have a huge password I have no interest in typing in lol

**Comment by ericmason** [comment]
Fixed. Apparently you have to have a menu bar for these things to work. https://github.com/electron/electron/issues/2402
